_target_: src.models.translate_module.TranslateLitModule

net:
  _target_: src.models.components.mini_translate.TranslateModel
  vocab_size: 250100
  encoder_layers: 6
  decoder_layers: 6
  embed_dim: 512
  num_heads: 8
  qkv_bias: true
  attn_drop: 0.02
  proj_drop: 0.02
  ffn_drop: 0.02

lr: 5e-4
warmup_ratio: 0.02
min_lr_rate: 0.1
compile: true